port: 9000
log_level: info

database:
  host: localhost
  port: 5432
  user: xiaozhu
  password: 12345679
  name: go_manage_starter
  schema: manage

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: default-jwt-secret-key
  expire_time: 24 # Deprecated: for backward compatibility
  access_token_expire: 30 # Access token expiration in minutes
  refresh_token_expire: 720 # Refresh token expiration in hours (30 days)
