ENVIRONMENT: development
PORT: 8080
LOG_LEVEL: info

# Development Database configuration
DB_HOST: localhost
DB_PORT: 5432
DB_USER: xiaozhu
DB_PASSWORD: 12345679
DB_NAME: go_manage_starter
DB_SCHEMA: manage_dev

# Development Redis configuration
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD:
REDIS_DB: 0

# Development JWT configuration
JWT_SECRET: dev-jwt-secret-key-change-this-in-production
JWT_EXPIRE_TIME: 24
