port: 8080
log_level: info

database:
  host: localhost
  port: 5432
  user: xiaozhu
  password: 12345679
  name: go_manage_starter
  schema: manage

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: default-jwt-secret-key
  expire_time: 24
