# 生产环境配置
environment: production
log_level: warn

database:
  host: prod-db.example.com
  port: 5432
  user: prod_user
  password: ${DB_PASSWORD} # 从环境变量读取
  name: go_manage_starter_prod
  schema: manage_prod

redis:
  host: prod-redis.example.com
  port: 6379
  password: ${REDIS_PASSWORD} # 从环境变量读取
  db: 0

jwt:
  secret: ${JWT_SECRET} # 从环境变量读取
  expire_time: 2 # 生产环境较短的过期时间（2小时）
